[package]
name = "agent-reviewer-model-provider"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
genai = { workspace = true, features = ["bedrock-sigv4"] }

serde = { workspace = true, features = ["derive"] }

thiserror = { workspace = true }

tracing = { workspace = true }
