[package]
name = "agent-reviewer-agent"
edition.workspace = true
version.workspace = true
license.workspace = true
license-file.workspace = true

[dependencies]
agent-reviewer-tools = { workspace = true }

genai = { workspace = true }

async-trait = { workspace = true }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
schemars = { workspace = true }

anyhow = { workspace = true }

tracing = { workspace = true }
