concurrency = 1

[[model_providers]]
id = "github"
type = "GitHub"

[[models]]
id = "gpt-4.1"
model = "openai/gpt-4.1"
provider = "github"

[[models]]
id = "gpt-4.1-mini"
model = "openai/gpt-4.1-mini"
provider = "github"

[[models]]
id = "gpt-4.1-nano"
model = "openai/gpt-4.1-nano"
provider = "github"

[[agents]]
id = "light"
model = "gpt-4.1-nano"
max_tokens = 10000

[[agents]]
id = "standard"
model = "gpt-4.1-mini"
effort = "medium"
max_tokens = 10000

[[agents]]
id = "power"
model = "gpt-4.1"
effort = "high"
max_tokens = 10000

[steps]
triage = {
    agent = "light"
}
review = {
    light = {
        main_agent = "light",
        adviser_agent = "standard",
        verifier_agent = "light"
    },
    standard = {
        main_agent = "standard",
        adviser_agent = "power",
        verifier_agent = "standard"
    },
    power = {
        main_agent = "power",
        verifier_agent = "power"
    }
}
finalize = {
    agent = "power"
}

[subagent.explorer]
agent = "light"
